import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { checkClimateStatus } from '../services/api';
import { useLanguage } from '../context/LanguageContext';
import { analyzeClimateVariance, getInstarAdvisory, INSTAR_CLIMATE_KNOWLEDGE } from '../services/climateAdvisories';
import './ClimateAdvisory.css';

function ClimateAdvisory() {
  const { t, lang } = useLanguage();
  const navigate = useNavigate();
  const [stage, setStage] = useState('Instar 3');
  const [temp, setTemp] = useState('27.0');
  const [humidity, setHumidity] = useState('88.0');
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState(null);
  const [error, setError] = useState(null);

  const stagesList = Object.keys(INSTAR_CLIMATE_KNOWLEDGE);

  const handleCheck = async (e) => {
    if (e) e.preventDefault();
    if (!temp || isNaN(temp) || parseFloat(temp) <= 0) {
      setError('Please enter a valid temperature value.');
      return;
    }
    if (!humidity || isNaN(humidity) || parseFloat(humidity) < 0 || parseFloat(humidity) > 100) {
      setError('Please enter a valid relative humidity percentage (0 - 100%).');
      return;
    }

    setError(null);
    setLoading(true);

    try {
      const res = await checkClimateStatus({ stage, temperature: parseFloat(temp), humidity: parseFloat(humidity) });
      if (res.success && res.data) {
        setReport(res.data);
      } else {
        setError(res.message || 'Failed to calculate climate status.');
      }
    } catch (err) {
      setError('Failed to compute climate advisory. Please verify server connectivity.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    handleCheck();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [stage]);

  const handlePreset = (presetStage, presetTemp, presetHum) => {
    setStage(presetStage);
    setTemp(presetTemp.toString());
    setHumidity(presetHum.toString());
  };

  const getStatusBadge = (status) => {
    if (status === 'SAFE') return { label: t('status_safe') || 'SAFE CONDITIONS', class: 'status-safe', icon: '✅' };
    if (status === 'WARNING') return { label: t('status_warning') || 'WARNING — ADJUSTMENT NEEDED', class: 'status-warning', icon: '⚠️' };
    return { label: t('status_critical') || 'CRITICAL — IMMEDIATE ACTION', class: 'status-critical', icon: '🚨' };
  };

  // Derive deterministic scientific analysis from our climate operations engine
  const variance = analyzeClimateVariance(stage, temp, humidity);
  const stageAdvisory = getInstarAdvisory(stage, lang);
  const overallStatus = report ? report.status : variance.overallStatus;
  const statusBadge = getStatusBadge(overallStatus);

  // WhatsApp Share Function for Climate Advisory
  const handleWhatsAppShareClimate = () => {
    const statusEmoji = {
      'SAFE': '✅',
      'WARNING': '⚠️',
      'CRITICAL': '🚨'
    }[overallStatus] || '📊';

    const message =
`🌡️ *SeriSense AI — Silkworm Climate Advisory Report*
━━━━━━━━━━━━━━━━━━━━━━
🐛 *Rearing Stage:* ${stage} (${stageAdvisory.stage_title || ''})
📈 *Climate Status:* ${statusEmoji} ${statusBadge.label}
━━━━━━━━━━━━━━━━━━━━━━
🌡️ *Room Temperature:* ${variance.currentTemp}°C (Optimal: ${variance.ideal_temp_min}–${variance.ideal_temp_max}°C)
💧 *Relative Humidity:* ${variance.currentHumidity}% (Optimal: ${variance.ideal_hum_min}–${variance.ideal_hum_max}%)
📊 *Temperature Variance:* ${variance.tempDelta === 0 ? 'Optimal' : `${variance.tempDelta > 0 ? '+' : ''}${variance.tempDelta}°C`}
📊 *Humidity Variance:* ${variance.humDelta === 0 ? 'Optimal' : `${variance.humDelta > 0 ? '+' : ''}${variance.humDelta}%`}
━━━━━━━━━━━━━━━━━━━━━━
🔬 *Biological Context & Risk:*
${stageAdvisory.biological_context}
⚠️ *Pathogen Risk:* ${stageAdvisory.pathogen_risks}

🛠️ *Practical Room Interventions:*
${Array.isArray(stageAdvisory.room_interventions)
  ? stageAdvisory.room_interventions.slice(0, 3).map((r, idx) => `${idx + 1}. ${r}`).join('\n')
  : 'See app for complete SOP'}

📋 *24-Hour Checklist:*
${Array.isArray(stageAdvisory.monitoring_checklist)
  ? stageAdvisory.monitoring_checklist.slice(0, 2).map((c, idx) => `☑ ${c}`).join('\n')
  : 'Follow standard monitoring routine'}
━━━━━━━━━━━━━━━━━━━━━━
🤖 _Generated by SeriSense AI_
_AI-Powered Sericulture Advisory_
_Sri Krishna College of Technology_`;

    const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`;
    window.open(whatsappUrl, '_blank');
  };

  return (
    <div className="climate-container">
      {/* Header */}
      <div className="page-header">
        <div className="header-icon">🌡️</div>
        <div>
          <h1 className="header-title">{t('climate_title') || 'Silkworm Rearing Climate Advisory'}</h1>
          <p className="header-subtitle">{t('climate_subtitle') || 'Microclimate environmental regulation & disease mitigation operations engine'}</p>
        </div>
        <div className="header-badge">
          <span className="badge-chip orange">{t('climate_ops_badge') || 'Rearing Operations Engine'}</span>
        </div>
      </div>

      <div className="climate-grid">
        {/* Left Column: Input Controls Card */}
        <div className="input-card">
          <h3 className="card-title">{t('enter_conditions') || '1. Enter Rearing Conditions'}</h3>
          <p className="card-desc">Select silkworm growth stage and input current room sensor readings</p>

          <form onSubmit={handleCheck}>
            {/* Stage Dropdown */}
            <div className="form-group">
              <label className="input-label">{t('instar_stage') || '🐛 Instar / Growth Stage'}</label>
              <select
                className="form-control select-input"
                value={stage}
                onChange={(e) => setStage(e.target.value)}
              >
                {stagesList.map((s) => (
                  <option key={s} value={s}>
                    {s} — {INSTAR_CLIMATE_KNOWLEDGE[s][lang]?.stage_title || INSTAR_CLIMATE_KNOWLEDGE[s].en.stage_title}
                  </option>
                ))}
              </select>
            </div>

            {/* Target info box */}
            <div className="target-info-box">
              <div className="target-title">{t('target_params_for') || 'Target Parameters for'} {stage}:</div>
              <div className="target-values">
                <span>🌡️ Temp: <strong>{variance.ideal_temp_min} - {variance.ideal_temp_max} °C</strong></span>
                <span>💧 Humidity: <strong>{variance.ideal_hum_min} - {variance.ideal_hum_max} %</strong></span>
              </div>
            </div>

            {/* Temp & Humidity inputs */}
            <div className="inputs-row">
              <div className="form-group">
                <label className="input-label">{t('room_temp') || '🌡️ Current Room Temp (°C)'}</label>
                <input
                  type="number"
                  step="0.1"
                  className="form-control"
                  placeholder="e.g. 27"
                  value={temp}
                  onChange={(e) => setTemp(e.target.value)}
                />
              </div>

              <div className="form-group">
                <label className="input-label">{t('room_humidity') || '💧 Current Humidity (%)'}</label>
                <input
                  type="number"
                  step="0.1"
                  className="form-control"
                  placeholder="e.g. 88"
                  value={humidity}
                  onChange={(e) => setHumidity(e.target.value)}
                />
              </div>
            </div>

            {/* Quick Test Presets */}
            <div className="preset-selector">
              <span className="preset-label">{t('preset_label') || 'Test Scenarios:'}</span>
              <div className="preset-buttons">
                <button
                  type="button"
                  className="preset-btn safe"
                  onClick={() => handlePreset('Instar 1', 27.0, 88.0)}
                >
                  {t('preset_safe') || '🟢 Safe Stage 1'}
                </button>
                <button
                  type="button"
                  className="preset-btn warning"
                  onClick={() => handlePreset('Instar 3', 29.0, 82.0)}
                >
                  {t('preset_high_temp') || '🟡 High Temp (30°C)'}
                </button>
                <button
                  type="button"
                  className="preset-btn critical"
                  onClick={() => handlePreset('Instar 5', 31.0, 92.0)}
                >
                  {t('preset_high_hum') || '🔴 High Humidity (95%)'}
                </button>
              </div>
            </div>

            {error && <div className="error-alert">⚠️ {error}</div>}

            <button type="submit" className="btn-submit orange-btn" disabled={loading}>
              {loading ? (
                <>
                  <span className="spinner orange-spin"></span> Evaluating Microclimate...
                </>
              ) : (
                t('calculate_advisory') || '⚡ Calculate Climate Advisory'
              )}
            </button>
          </form>
        </div>

        {/* Right Column: 5-Tier Decision-Support Operations Dashboard */}
        <div className="result-card">
          <div className="climate-operations-report">
            {/* Top Banner */}
            <div className={`status-banner ${statusBadge.class}`}>
              <div className="status-header">
                <span className="status-icon">{statusBadge.icon}</span>
                <div>
                  <h2 className="status-title">{statusBadge.label}</h2>
                  <p className="status-sub">
                    {stage} · {stageAdvisory.stage_title}
                  </p>
                </div>
              </div>
            </div>

            {/* Tier 1: Parameter Variance Matrix */}
            <div className="ops-card section-variance">
              <div className="ops-card-header">
                <span className="ops-icon">📊</span>
                <h4>{t('climate_variance_title') || 'Thermal & Humidity Variance Analysis'}</h4>
              </div>
              <div className="variance-grid">
                {/* Temperature Card */}
                <div className={`variance-item var-${variance.tempStatus}`}>
                  <div className="var-header">
                    <span className="var-title">🌡️ Temperature</span>
                    <span className={`var-pill pill-${variance.tempStatus}`}>
                      {variance.tempDelta === 0 ? t('variance_optimal') : `${variance.tempDelta > 0 ? '+' : ''}${variance.tempDelta} °C`}
                    </span>
                  </div>
                  <div className="var-metrics">
                    <span className="metric-current">{variance.currentTemp}°C</span>
                    <span className="metric-target">Target: {variance.ideal_temp_min} – {variance.ideal_temp_max}°C</span>
                  </div>
                  {report?.temperature_correction && (
                    <p className="var-correction">{report.temperature_correction}</p>
                  )}
                </div>

                {/* Humidity Card */}
                <div className={`variance-item var-${variance.humStatus}`}>
                  <div className="var-header">
                    <span className="var-title">💧 Relative Humidity</span>
                    <span className={`var-pill pill-${variance.humStatus}`}>
                      {variance.humDelta === 0 ? t('variance_optimal') : `${variance.humDelta > 0 ? '+' : ''}${variance.humDelta} %`}
                    </span>
                  </div>
                  <div className="var-metrics">
                    <span className="metric-current">{variance.currentHumidity}%</span>
                    <span className="metric-target">Target: {variance.ideal_hum_min} – {variance.ideal_hum_max}%</span>
                  </div>
                  {report?.humidity_correction && (
                    <p className="var-correction">{report.humidity_correction}</p>
                  )}
                </div>
              </div>
            </div>

            {/* Tier 2: Biological Vulnerability & Pathology */}
            <div className="ops-card section-pathology">
              <div className="ops-card-header">
                <span className="ops-icon">🔬</span>
                <h4>{t('section_biological_vuln') || 'Stage Biological Vulnerability & Pathology'}</h4>
              </div>
              <p className="biological-intro">{stageAdvisory.biological_context}</p>
              <div className="pathogen-risk-box">
                <span className="risk-tag">⚠️ Critical Vulnerability:</span>
                <p className="risk-text">{stageAdvisory.pathogen_risks}</p>
              </div>
            </div>

            {/* Tier 3: Practical Physical Interventions (SOP) */}
            <div className="ops-card section-interventions">
              <div className="ops-card-header">
                <span className="ops-icon">🛠️</span>
                <h4>{t('section_room_interventions') || 'Practical Physical Interventions (Room Climate SOP)'}</h4>
              </div>
              <ol className="intervention-steps">
                {stageAdvisory.room_interventions.map((step, idx) => (
                  <li key={idx} className="intervention-step-item">
                    <span className="step-badge">{idx + 1}</span>
                    <span className="step-desc">{step}</span>
                  </li>
                ))}
              </ol>
            </div>

            {/* Tier 4: 24-Hour Checklist */}
            <div className="ops-card section-checklist">
              <div className="ops-card-header">
                <span className="ops-icon">📋</span>
                <h4>{t('section_monitoring_check') || '24-Hour Rearing Bed Checklist & Next Steps'}</h4>
              </div>
              <ul className="checklist-items">
                {stageAdvisory.monitoring_checklist.map((item, idx) => (
                  <li key={idx}>
                    <span className="check-box">☑</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* WhatsApp Share Button */}
            <div className="whatsapp-share-bar" style={{ margin: '14px 0 10px' }}>
              <button
                type="button"
                onClick={handleWhatsAppShareClimate}
                style={{
                  width: '100%',
                  padding: '12px 18px',
                  borderRadius: '12px',
                  fontWeight: '700',
                  fontSize: '0.98rem',
                  border: 'none',
                  cursor: 'pointer',
                  background: 'linear-gradient(135deg, #25D366, #128C7E)',
                  color: '#ffffff',
                  boxShadow: '0 4px 14px rgba(37, 211, 102, 0.3)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '10px',
                  transition: 'all 0.2s ease'
                }}
                onMouseOver={e => {
                  e.currentTarget.style.transform = 'translateY(-2px)';
                  e.currentTarget.style.boxShadow = '0 6px 18px rgba(37, 211, 102, 0.4)';
                }}
                onMouseOut={e => {
                  e.currentTarget.style.transform = 'translateY(0)';
                  e.currentTarget.style.boxShadow = '0 4px 14px rgba(37, 211, 102, 0.3)';
                }}
              >
                <span style={{ fontSize: '1.2rem' }}>📲</span>
                {t('btn_share_whatsapp') || 'Share Advisory Report on WhatsApp'}
              </button>
            </div>

            {/* Tier 5: Audit Trail & History Link */}
            <div className="climate-history-footer">
              <span className="history-status">
                ✅ Recorded in Cloud Firestore Rearing History
              </span>
              <button
                type="button"
                className="btn-history-view"
                onClick={() => navigate('/history?tab=climate')}
              >
                {t('btn_view_climate_history') || '📜 View Climate Log in History'}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ClimateAdvisory;